Clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('posts/', include("posts.urls")),
    path('shifts/', include("turn.urls")),
]
if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

#from posts import views as ...
app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_function, name='login'),
    path('logout/', views.logout_function, name='logout'),
    path('signup/doctor', views.signup_doctor_function, name='signup-doctor'),
    path('signup/sick', views.signup_sick_function, name='signup-sick'),
    path('account', views.account, name='account'),
    path('account/edit', views.edit, name='edit'),

    path('doctor-manage', views.doctor_management, name='doctor-manage'),
    path('doctor-manage/<int:id>/delete', views.doctor_delete, name='doctor-delete'),
    path('doctor-cash-list', views.doctor_cash_list, name='doctor-cash-list'),

    path('sick-manage', views.sick_management, name='sick-manage'),
    path('sick-manage/<int:id>/delete', views.sick_delete, name='sick-delete'),
    path('sick-cash-list', views.sick_cash_list, name='sick-cash-list'),

    path('', views.home, name='home'),
]

turn/urls.py
from django.urls import path
from . import views


app_name = 'turn'
urlpatterns = [

#for sicks
    path('list/', views.shift_list_for_sick, name='list'),
    path('<int:id>/set-turn/', views.set_turn_for_sick, name='set-turn'),
    path('passed/', views.passed_for_sick, name='passed'),
    path('load/', views.load_for_sick, name='load'),
    path('cash/increase', views.increase_cash_for_sick_list, name='cash-increase'),
    path('cash/increase/<int:amount>/', views.increase_cash_for_sick, name='cash-increase-amount'),
    path('cash/', views.cash_for_sick, name='sick-cash'),

#for doctors 
	path('my-shifts/', views.shift_list_for_doctor, name='doctor-shifts'),
	path('<int:id>/', views.take_visite, name='shift'),
	path('my-passed-turns/', views.passed_for_doctor, name='doctor-passed-turns'),
	path('my-cash-list/', views.cash_for_doctor, name='doctor-cashes'),

#for staff
	path('create/', views.create_shift, name='shift-create'),
	path('<int:id>/edit', views.edit_shift, name='shift-edit'),
	path('<int:id>/delete', views.delete_shift, name='shift-delete'),
	path('<int:id>/detail', views.detail_shift, name='shift-delete'),
	path('manage/', views.manage, name='shift-manage'),
	path('passed-shifts/', views.passed_shifts, name='shift-passed'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from .managers import UserManager
from django.urls import reverse
from django.conf import settings 

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('Email Address', unique=True)
    date_joined = models.DateTimeField('Date Joined', auto_now_add=True)
    is_active = models.BooleanField('Active', default=True)
    objects = UserManager()
    is_staff = models.BooleanField('Staff Status',default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_name(self):
        full_name = '%s' % (self.name)
        return full_name.strip()

    def get_url(self):
        return reverse("accounts:home")



class Doctor(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	id_number = models.IntegerField(unique=True)
	name = models.CharField(max_length=50)
	phone = models.IntegerField()
	cash = models.PositiveIntegerField(default=0)

	def __str__(self):
		return str(self.name)

	def get_url(self):
		return reverse("accounts:home")


class Sick(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	id_number = models.IntegerField(unique=True)
	name = models.CharField(max_length=50)
	phone = models.IntegerField()
	cash = models.PositiveIntegerField(default=0)

	def __str__(self):
		return str(self.name)
		
	def get_url(self):
		return reverse("accounts:home")




class Staff(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	id_number = models.IntegerField(default=0)
	name = models.CharField(max_length=50)
	phone = models.IntegerField(default=0)

	def __str__(self):
		return str(self.name)

	def get_url(self):
		return reverse("accounts:home")

accounts/forms.py
from django import forms
from .models import User,Sick,Doctor
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput,label="Email")
    password = forms.CharField(widget=forms.PasswordInput,label="Password")

    def clean_password(self):
        password = self.cleaned_data['password']
        email = self.cleaned_data['email'].lower()
        users = User.objects.filter(email=email)
        if users.count() :
            user = User.objects.get(email=email)
            if user.check_password(password):
                return password
            else :
                raise ValidationError("گذرواژه شما صحیح نمی باشد")
        else : 
            raise ValidationError("کاربری با این اطلاعات یافت نشد")

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        return email


class SignupForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput,label="Email")
    password = forms.CharField(widget=forms.PasswordInput,label="Password")
    name = forms.CharField()
    id_number = forms.IntegerField()
    phone = forms.IntegerField()

    def clean_email(self): 
        email = self.cleaned_data['email'].lower()
        exists = User.objects.filter(email=email)
        if exists.count():
            raise ValidationError("این ایمیل از قبل ثبت نام شده است")
        return email
 
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password)<4:
                raise ValidationError("گذرواژه حداقل باید شامل 4 کاراکتر باشد")
        return password



class EditForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput,label="Email")
    password = forms.CharField(widget=forms.PasswordInput,label="Password")
    name = forms.CharField()
    id_number = forms.IntegerField()
    phone = forms.IntegerField()
 
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password)<4:
                raise ValidationError("گذرواژه حداقل باید شامل 4 کاراکتر باشد")
        return password
    
    
        

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from .models import User, Sick, Doctor
from .forms import UserLoginForm, SignupForm, EditForm
from posts.models import Post
from turn.models import Shift, Turn
from .decorators import staff_required
# Create your views here.


def home(request):
    posts = Post.objects.all()
    query = request.GET.get("q")
    if query:
        posts = posts.filter(
            Q(title__icontains=query) |
            Q(context__icontains=query)
        ).distinct()
    return render(request, "accounts/home.html", {"posts": posts})


@login_required
@staff_required
def doctor_management(request):
    all_doctors = Doctor.objects.all()
    doctors = []
    for doctor in all_doctors:
        doctors.append([doctor, Shift.objects.filter(doctor=doctor).count()])
    return render(request, "accounts/doctor-manage.html", {"doctors": doctors})


@login_required
@staff_required
def doctor_delete(request, id=None):
    doctor = get_object_or_404(Doctor, id=id)
    user = doctor.user
    doctor.delete()
    user.delete()
    messages.success(request, "دکتر مورد نظر با موفقیت حذف گردید")
    return HttpResponseRedirect(reverse("accounts:doctor-manage"))


@login_required
@staff_required
def sick_management(request):
    all_sick = Sick.objects.all()
    sicks = []
    for sick in all_sick:
        sicks.append([sick, Turn.objects.filter(sick=sick).count()])
    return render(request, "accounts/sick-manage.html", {"sicks": sicks})


@login_required
@staff_required
def sick_delete(request, id=None):
    sick = get_object_or_404(Sick, id=id)
    user = sick.user
    sick.delete()
    user.delete()
    messages.success(request, "بیمار مورد نظر با موفقیت حذف گردید")
    return HttpResponseRedirect(reverse("accounts:sick-manage"))


@login_required
@staff_required
def doctor_cash_list(request):
    all_doctors = Doctor.objects.all()
    doctors = []
    for doctor in all_doctors:
            total = 0
            for shift in Shift.objects.filter(doctor=doctor):
                total += shift.turn_set.filter(
                    is_passed=True).count()*shift.cash
            doctors.append([doctor, total])
            print(total)
    return render(request, "accounts/doctor-manage.html", {"doctors": doctors, "readonly": True})


@login_required
@staff_required
def sick_cash_list(request):
    all_sick = Sick.objects.all()
    sicks = []
    for sick in all_sick:
        sicks.append([sick, Turn.objects.filter(sick=sick).count()])
    return render(request, "accounts/sick-manage.html", {"sicks": sicks, "readonly": True})


@login_required
def account(request):
    return render(request, "accounts/account.html", {})


def login_function(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(request.user.get_url())
    form = UserLoginForm()
    if request.POST:
        form = UserLoginForm(request.POST or None)
        if form.is_valid():
            user = User.objects.get(email=form.clean_email())
            login(request, user)
            return HttpResponseRedirect(reverse("accounts:home"))
    return render(request, "accounts/login.html", {"form": form})


@login_required
def logout_function(request):
    logout(request)
    return HttpResponseRedirect(reverse("accounts:home"))


def signup_sick_function(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(request.user.get_url())

    form = SignupForm()
    if request.POST:
        form = SignupForm(request.POST or None)
        if form.is_valid():
            user = User.objects.create_user(
                email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            sick = Sick()
            sick.name = form.cleaned_data.get('name')
            sick.id_number = form.cleaned_data.get('id_number')
            sick.phone = form.cleaned_data.get('phone')
            sick.user = user
            user.save()
            sick.save()
            user = authenticate(username=user.email,
                                password=form.cleaned_data['password'])
            login(request, user)
            messages.success(request, "ثبت نام شما با موفقیت انجام شد")
            return HttpResponseRedirect(reverse("accounts:account"))

    return render(request, "accounts/editorsignup.html", {"form": form, "sick": True})


def signup_doctor_function(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(request.user.get_url())
    form = SignupForm()
    if request.POST:
        form = SignupForm(request.POST or None)
        if form.is_valid():
            user = User.objects.create_user(
                email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            doctor = Doctor()
            doctor.name = form.cleaned_data.get('name')
            doctor.id_number = form.cleaned_data.get('id_number')
            doctor.phone = form.cleaned_data.get('phone')
            doctor.user = user
            user.save()
            doctor.save()
            user = authenticate(username=user.email,
                                password=form.cleaned_data['password'])
            login(request, user)
            messages.success(request, "ثبت نام شما با موفقیت انجام شد")
            return HttpResponseRedirect(reverse("accounts:account"))

    return render(request, "accounts/editorsignup.html", {"form": form})


@login_required
def edit(request):
    user = request.user
    if hasattr(user, "staff"):
        instance = user.staff
    elif hasattr(user, "sick"):
        instance = user.sick
    else:
        instance = user.doctor

    form = EditForm()
    if request.POST:
        form = EditForm(request.POST or None)
        if form.is_valid():
            user.email = form.cleaned_data.get('email')
            user.set_password(form.cleaned_data.get('password'))
            instance.name = form.cleaned_data.get('name')
            instance.id_number = form.cleaned_data.get('id_number')
            instance.phone = form.cleaned_data.get('phone')
            user.save()
            instance.save()
            user_login = authenticate(username=form.cleaned_data.get(
                'email'), password=form.cleaned_data.get('password'))
            login(request, user_login)
            messages.success(request, "ویرایش شما با موفقیت انجام شد")
            return HttpResponseRedirect(reverse("accounts:account"))

    return render(request, "accounts/editorsignup.html", {"form": form, "readonly": True, "instance": instance})

templates/accounts/account.html
{% extends "base.html"%} {% block content %}

<div class="m-2">
    <div class="card">
        <section class="font font-bbcnassim-all" style=" text-align: right; ">
            <div class="card-header p-b-0">
                <section class="font font-bbcnassim-eot" style="text-align: right;">
                    <h5 class="bold">مشاهده پروفایل <i class="fa fa-eye"></i></h5>
                </section>
            </div>
            <div class="card-block">
                <div class="m-2">
                    <article>
                        <div class="m-2">

                            <section class="font font-bbcnassim-eot" style=" text-align: right;">
                                {%if messages %} {%for message in messages%}
                                <div class="alert alert-info alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> {{message}}
                                </div>
                                {% endfor %} {% endif %}
                                <dl class="row">
                                    <dd class="col-sm-8">{%if request.user.sick %}{{request.user.sick.name}} {% else %}{{request.user.doctor.name}} {% endif %} {%if request.user.staff %}{{request.user.staff.name}} {% endif %}</dd>
                                    <dt class="col-sm-4">نام و نام خانوادگی</dt>
                                </dl>


                                <dl class="row">
                                    <dd class="col-sm-8">{%if request.user.sick %}{{request.user.sick.id_number}} {% else %}{{request.user.doctor.id_number}} {% endif %} {%if request.user.staff %}{{request.user.staff.id_number}} {% endif %}</dd>
                                    <dt class="col-sm-4">کد ملی</dt>
                                </dl>


                                <dl class="row">
                                    <dd class="col-sm-8">{{request.user.email}}</dd>
                                    <dt class="col-sm-4">پست الکترونیک</dt>
                                </dl>


                                <dl class="row">
                                    <dd class="col-sm-8">{%if request.user.sick %}بیمار {% else %}پزشک {% endif %} {%if request.user.staff %}مسئول فنی {% endif %}</dd>
                                    <dt class="col-sm-4">سمت</dt>
                                </dl>


                                <dl class="row">
                                    <dd class="col-sm-8">{%if request.user.sick %}{{request.user.sick.phone}} {% else %}{{request.user.doctor.phone}} {% endif %} {%if request.user.staff %}{{request.user.staff.phone}} {% endif %}</dd>
                                    <dt class="col-sm-4">شماره تماس</dt>
                                </dl>

                            </section>
                            <section class="font font-bbcnassim-eot" style=" text-align: right;">
                                <a href="/account/edit"><button class="btn btn-primary"><div class="bold">ویرایش</div></button></a>
                                <a href="/"><button class="btn btn-danger"><div class="bold">بازگشت</div></button></a>
                            </section>

                        </div>
                    </article>
                </div>
            </div>
        </section>
    </div>
</div>

{%endblock%}

templates/accounts/doctor-manage.html
{% extends "base.html"%} {% block content %}
<div class="m-2">
    {%if messages %}
    <section class="font font-bbcnassim-all" style=" text-align: right; ">{%for message in messages%}
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> {{message}}
        </div>
        {% endfor %} </section>{% endif %}

    <div class="card">
        <section class="font font-bbcnassim-all" style=" text-align: right; ">
            <div class="card-header p-b-0">
                <section class="font font-bbcnassim-eot" style="text-align: right;">
                    <h5 class="bold">مشاهده و مدیریت لیست پزشکان <i class="fas fa-briefcase-medical"></i></h5>
                </section>
            </div>
            <div class="card-block">
                <div class="m-2">
                    <article>
                        <div class="m-3">
                            <section class="font font-bbcnassim-eot" style=" direction: rtl; text-align: right;">

                                <table class="table table-bordered table-hover table-light">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>ردیف</th>
                                            <th>نام پزشک</th>
                                            {% if not readonly %}
                                            <th>تعداد ویزیت ها</th>
                                            <th>رایانامه</th>
                                            <th>شماره تلفن</th>
                                            <th>شماره ملی</th>
                                            <th>حذف پزشک</th>
                                            {% else %}
                                            <th>رایانامه</th>
                                            <th>مقدار کل پرداختی</th>
                                            {% endif %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for doctor,visite in doctors %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{doctor.name}}</td>
                                            {% if not readonly %}
                                            <td>{{visite}}</td>
                                            <td>{{doctor.user.email}}</td>
                                            <td>{{doctor.phone}}</td>
                                            <td>{{doctor.id_number}}</td>
                                            <td><a href="/doctor-manage/{{doctor.id}}/delete"><button class="btn btn-danger" onclick="return confirm('برای حذف دکتر مطمئن هستید؟');">حذف پزشک</button></a></td>
                                            {% else %}
                                            <td>{{doctor.user.email}}</td>
                                            <th>{{ visite }} تومان</th>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </section>
                        </div>
                    </article>
                </div>
            </div>
        </section>
    </div>
</div>

{%endblock%}

templates/accounts/editorsignup.html
{% extends "base.html"%} {% block content %}
<div class="m-2">
    <div class="card">
        <section class="font font-bbcnassim-all" style=" text-align: right; ">
            <div class="card-header p-b-0">
                <section class="font font-bbcnassim-eot" style="text-align: right;">
                    {% if readonly %}
                    <h5 class="bold">ویرایش {%if request.user.sick %}بیمار {% endif %} {% if request.user.doctor %}پزشک {% endif %} {%if request.user.staff %}مسئول فنی {% endif %}<i class="fa fa-edit"></i></h5>
                    {% else %}
                    <h5 class="bold">ثبت نام {%if sick %}بیمار {% else %}پزشک {% endif %} <i class="fas fa-user-plus"></i></h5>
                    {% endif %}
                </section>
            </div>
            <div class="card-block">
                <div class="m-2">
                    <article>

                        <div class="m-2">
                            <section class="font font-bbcnassim-eot" style=" direction: rtl; text-align: right;">

                                {% if form.errors %} {% for field in form %} {% for error in field.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{error}}
                                </div>
                                {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{error}}
                                </div>
                                {% endfor %} {% endif %}

                                <form class="form" method="POST">{% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-3 col-form-label mr-2"><div class="bold">نام و نام خانوادگی</div></label>
                                        <div class="col-8">
                                            <input type="text" class="form-control " id="id_name" name="name" placeholder="نام و نام خانوادگی خود را وارد کنید" required {% if readonly%} value="{{instance.name}}" {% endif %}>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label mr-2"><div class="bold">کد ملی</div></label>
                                        <div class="col-8">
                                            <input type="number" class="form-control " id="id_id_number" name="id_number" placeholder="کد ملی خود را وارد کنید" required {% if readonly%}readonly value="{{instance.id_number}}" {% endif %}>
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-3 col-form-label mr-2"><div class="bold">پست الکترونیک</div></label>
                                        <div class="col-8">
                                            <input type="email" class="form-control" id="id_email" name="email" placeholder="E-mail خود را وارد کنید" required {% if readonly%}readonly value="{{request.user.email}}" {% endif %}>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label mr-2"><div class="bold">سمت</div></label>
                                        <div class="col-6">
                                            <p class="form-control-plaintext">{%if sick %}بیمار {% else %}پزشک {% endif %}</p>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label mr-2"><div class="bold">شماره تماس</div></label>
                                        <div class="col-8">
                                            <input type="tel" class="form-control" placeholder="شماره تماس خود را با پیش کد وارد کنید" id="id_phone" name="phone" required{% if readonly%} value="{{instance.phone}}" {% endif %}>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label mr-2"><div class="bold">گذرواژه</div></label>
                                        <div class="col-8">
                                            <input type="password" class="form-control" placeholder="گذرواژه خود را وارد کنید" required id="id_password" name="password" required>
                                        </div>
                                    </div>

                                    <a href="/account" class="btn btn-danger">
                                        <div class="bold">انصراف</div>
                                    </a> {%if request.user.is_authenticated%}
                                    <button type="submit" class="btn btn-primary"><div class="bold">ثبت تغییرات</div></button> {% else %}
                                    <button type="submit" class="btn btn-primary"><div class="bold">ثبت نام</div></button> {% endif %}

                                </form>
                            </section>
                        </div>
                    </article>
                </div>
            </div>
        </section>
    </div>
</div>
{%endblock%}

templates/accounts/login.html
{% extends "base.html"%} {% block content %}
<div class="m-2">
    <div class="card">
        <div class="card-header p-b-0">
            <h5 class="card-title">
                <section class="font font-bbcnassim-eot" style="direction: rtl; text-align: right;">
                    <div class="bold">
                        <i class="fa fa-sign-in-alt"></i> کاربران پرتال
                    </div>
                </section>
            </h5>
        </div>
        <div class="card-block">
            <div class="m-3">
                <section class="font font-bbcnassim-eot" style="direction: rtl; text-align: right;">
                    {% if form.errors %} {% for field in form %} {% for error in field.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{error}}
                    </div>
                    {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{error}}
                    </div>
                    {% endfor %} {% endif %}
                    <form action="" method="POST"> {% csrf_token %}
                        <div class="form-group">
                            <input type="email" class="form-control" id="id_email" name="email" placeholder="نام کاربری (E-mail یا کد ملی)" required="این فیلد اجباری است">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="id_password" name="password" placeholder="گذرواژه" required="این فیلد اجباری است">
                        </div>
                        <button type="submit" class="btn btn-success"><div class="bold">ورود به پرتال</div></button>
                    </form>
                </section>
                <section class="font font-bbcnassim-eot">
                    <a href="/signup/sick"><button class="btn btn-primary"><div class="bold">ثبت نام بیمار</div></button></a>
                    <a href="/signup/doctor"><button class="btn btn-primary"><div class="bold">ثبت نام پزشک</div></button></a>
                </section>
            </div>
        </div>
    </div>
</div>

{% endblock content %}